### ISSUE TITLE
[Feature request] ARM64 Linux builds

### ISSUE THREAD

**Issue by FalsePhilosopher** [flipperdevices/qFlipper#110]
It would be cool to be able to manage your FZ from an arm device like an rpi4, pinephone or other 64 bit arm device. Also is there any way to have a 4th menu tab that has a window that exposes the CLI interface to be played with?

**Comment by gsurkov** [comment]
Unfortunately, we cannot support every possible architecture in the official builds. Please address this issue to the maintainers of the distro you are using.
There are also currently no plans of adding the CLI in qFlipper because implementing it properly is not a trivial task. However, we would accept a pull request with this feature.
Please feel free to report any other bugs and don't forget to create a separate ticket per bug/request.
