### ISSUE TITLE
Bad text rendering on Qt6

### ISSUE THREAD

**Issue by LBlaboon** [flipperdevices/qFlipper#122]
Text renders incorrectly when building with Qt6. Potentially an issue with native text rendering.

**Describe the bug**
When building the application with Qt6, certain fonts appear to be rendered incorrectly (the pixel art fonts in particular).

**To Reproduce**
1. Build the application with Qt6
2. Launch the application
3. The text "Connect your flipper" is rendered incorrectly (among others)

**Expected behavior**
Text should render correctly as it does in Qt5.

**Actual behavior**
Certain pixel fonts render incorrectly which makes the text illegible, as in this screenshot:
![screenshot](https://user-images.githubusercontent.com/8608488/191545403-d34f3532-1ae0-4ada-a937-80966b96fc7c.png)

**Additional troubleshooting**
This appears to be related to the native text rendering in QtQuick. If I disable it by removing line 164 in `application/application.cpp` then text rendering looks fine.

**Additional context**
I am building this on Arch Linux using the latest available Qt6 libraries (currently, 6.3.2)

**Comment by gsurkov** [comment]
This is a known bug (at least on Arch, since qFlipper is being developed under it) (that's why the official binaries are still Qt5-based)
Most likely an upstream issue.

It can be somewhat mitigated by either using the internal Qt text rendering (but it blurs the pixelart-style fonts) or by enabling antialiasing with Native text rendering (which has the same effect).

One possible cause can be Arch-specific incorrect fotconfig configuration, albeit that's unlikely.
Finding a least obnoxious solution to this problem is in the nearest plans.

**Comment by gsurkov** [comment]
Qt's bug tracker has at least two bug reports ([one](https://bugreports.qt.io/browse/QTBUG-103750), [two](https://bugreports.qt.io/browse/QTBUG-107038)), but there seems to be no associated activity at all.

For now, I have enabled text anti-aliasing for Qt6-based builds on linux and tweaked some code to avoid fractional coordinates. It gets rid of the rendering problem, but the sharpness of the fonts will depend on user settings (e.g. subpixel smoothing, hinting, etc).

Still better than nothing, until they fix it for good.
