### ISSUE TITLE
OS Version wrong in logs

### ISSUE THREAD

**Issue by ctrlcmdshft** [flipperdevices/qFlipper#164]
Running Windows 11 version 22H2 (Build 22621.1344) and this is what qflipper is stating 

```
[APP] qFlipper version 1.2.2 commit ba67025d 2022-12-08T07:31:11
[APP] OS info: Windows 10 Version 2009 10 10.0.22621 Qt 5.15.2
```

**Comment by gsurkov** [comment]
@ctrlcmdshft It's a Windows 11 "[feature](https://techcommunity.microsoft.com/t5/windows-11/windows-11-registry-still-reports-windows-10-as-os-name/m-p/2812649)" for compatbility with older software that does OS version checks but knows nothing about Windows 11.

qFlipper is only displaying what the underlying system is reporting (which it does via the Qt library). 

As the development version was recently upgraded to Qt version 6 instead of 5, there is a chance that the newer Qt already includes some workaround for it.

Could you please test the development version and see if the bug still exists?

**Comment by ctrlcmdshft** [comment]
where can i find the development version for windows

**Comment by gsurkov** [comment]
@ctrlcmdshft [Here](https://update.flipperzero.one/builds/qFlipper/dev/).

**Comment by ctrlcmdshft** [comment]
You were correct bug no longer exists with that dev release  

```
[APP] qFlipper version 1.3.0-rc1 commit 2e99946c 2023-03-09T06:29:19
[APP] OS info: Windows 11 Version 22H2 11 10.0.22621 Qt 6.4.2
```
