### ISSUE TITLE
Not native fileDialog on kde linux

### ISSUE THREAD

**Issue by dunaevai135** [flipperdevices/qFlipper#35]
Install from file  вызывает fileDialog, который не умеет сортировку по дате, не умеет в сетевые папки.
1. click "Install from file"

![Screenshot_20211223_153919](https://user-images.githubusercontent.com/11465382/147353057-aa5d2a29-a4f6-4dff-9af2-53278f339cb1.png)

**Expected behavior**
Нативный системный fileDialog. Пример из Telegram, есть история откуда взят предыдущий файл, не надо начинать с home, работают сетевые папки и видны bookmarked places:
![Screenshot_20211223_154008](https://user-images.githubusercontent.com/11465382/147353104-f61bd70d-6700-4295-b407-ebc0c460f87d.png)
Пример на QT:
![Screenshot_20211223_154243](https://user-images.githubusercontent.com/11465382/147353374-618bf32d-b672-4d01-b424-0b6930d813a6.png)

Тут обсуждают такую же проблему в openshot, говорят, проблема в AppImages
https://github.com/OpenShot/openshot-qt/issues/3862

**Comment by gsurkov** [comment]
Проблема действительно в том, что поставка идет в пакете AppImage. Быстрый гуглинг показал, что с большой вероятностью нет способа заставить AppImage ходить через XDG портал и тем самым использовать нативный диалог.

Решением может быть либо сборка нативного пакета (который будет использовать системные библиотеки), либо использование более продвинутых пакетов типа Flatpak (последнее запланировано на будущее как альтернативный вариант поставки).

Если кто-то поделится инфой, как это сделать с помощью AppImage или даже сделает пулл-реквест, буду только рад.


The problem lies indeed within the AppImage format. A quick search revealed no practical ways of makig the AppImage use the XDG portal and thus use the native file picker.

As  a possible solution one may build a native package (which would use the system libraries) or use a more advanced package format like Flatpak (the latter is planned as an alternative download format).

If anyone is willing to share some info on acheiving this with AppImage or even make a pull request, I would be much grateful.
