### ISSUE TITLE
Windows 7/8 support

### ISSUE THREAD

**Issue by RChadwick7** [flipperdevices/qFlipper#71]
Hopefully qFlipper will support installation on Windows 7/8/8.1.

**Comment by zhovner** [comment]
The last update of windows 7 is 11 years ago. How many modern applications you can run on Windows 7? 
For us it will require a lot of work to support this OS. Since qFlipper is open source, you can try to build it for Windows 7 by yourself.

Right now we have a lot of work to do instead of spending time on this. If you can't use qFlipper, I recommend you to install virtual machine with modern OS like Linux/Windows, or try to update firmware over mobile app for Android/iOS https://flpr.app. But keep in mind that updating firmware from mobile app will work only after update to latest version from qFlipper.
