### ISSUE TITLE
Custom builds are not well handled

### ISSUE THREAD

**Issue by SamuelYvon** [flipperdevices/qFlipper#79]
**Describe the bug**
If you flash a custom firmware version, qFlipper will detect an unknown firmware, but will not suggest an update (it seems to think it's at the latest version)

**To Reproduce**
1. Flash a custom build
2. Open qFlipper
3. The update button is grayed out

**Expected behavior**
I expected the update button to be available, an unknown firmware is not equal to the latest

**Actual behavior**
The update button is unavailable

**The report *must* also include at least one of the following:**
A screenshot of the application window:
![Screenshot from 2022-05-28 15-28-34](https://user-images.githubusercontent.com/12652003/170840365-861ce1d3-6233-4819-bd71-a9f4d217e14e.png)

**Additional context**

Maybe this is wanted, in that case, feel free to discard this issue. But in my opinion, if the version is detected as unknown, it should suggest and update. I am aware it is possible to force an update through the GUI, but from a usability perspective, I'm not sure this is the best behavior.

**Comment by zhovner** [comment]
Thanks, will check this.
Thats because qFlipper cannot check the version. Try to swtich to `dev` channel.

**Comment by SamuelYvon** [comment]
> Thanks, will check this.

I would not mind taking care of this if you want (I'd enjoy it)

> Thats because qFlipper cannot check the version. Try to swtich to dev channel.

What I'm gathering is that because the flipper firmware is forked off the dev channel, it's not working with the release version? If I were to make a custom build of release, it would work?

**Comment by gsurkov** [comment]
Could you please link the .dfu file you are flashing? (so that we are on the same page).

The logic that decides how to treat the combination of Flipper's firmware and the user's choices is quite convoluted and was not  extensively tested with unofficial builds.
At the very least, it should display a non-coloured "Install" button in this particular case, so I consider this as a bug.

**Comment by SamuelYvon** [comment]
I don't have the DFU files with me right now, but you can build latest of https://github.com/SamuelYvon/flipperzero-firmware/tree/gpio-cli

**Comment by gsurkov** [comment]
The problem was in the method that converted the git branch to update channel name. A custom firmware was mistakenly considered as a release one.

Now the correct behaviour is to not attempt to decide whether a custom firmware can be updated and just show the "Install" button everywhere.

Could you please test the [dev version](https://update.flipperzero.one/builds/qFlipper/dev/) to confirm that the problem was fixed?

**Comment by SamuelYvon** [comment]
![image](https://user-images.githubusercontent.com/12652003/171860105-43c2a2b8-ccff-4810-a37e-c5de01ef7198.png)

I now have an unknown firmware, but I can update to latest. Seems good to me!
