### ISSUE TITLE
qFlipper 1.1.1 window flickers (AppImage / Debian 10  / i3wm)

### ISSUE THREAD

**Issue by romainricard** [flipperdevices/qFlipper#98]
Hello! 

**Describe the bug**
The whole qFlipper window flickers irregularly during normal operations (and not only _during opening, closing or resizing of the log area_, as explained in the README)

**To Reproduce**
1. Set up Debian 10
2. Download the latest qFlipper AppImage
3. Open qFlipper

**Expected behavior**
The interface should not flicker

**Actual behavior**
The whole interface flickers, making using the app painful to use

**Additional troubleshooting**
1. The app flickers even before a Flipper is connected (cf. video)
2. This behaviour does **not** appear on a Debian 11 computer (with i3wm)
3. qFlipper 1.1.0 also exhibits this buggy behaviour

**Video**
[Video](https://user-images.githubusercontent.com/7778898/182419692-f2b4bd6f-8d0e-4c67-8ae9-ca24e8b3a5c8.mp4)

**Full log**
[qFlipper-20220802-175404.txt](https://github.com/flipperdevices/qFlipper/files/9243782/qFlipper-20220802-175404.txt)

**System config**

```
$ uname -a
Linux xxx 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

$ i3 --version
i3 version 4.16.1 (2019-01-27) © 2009 Michael Stapelberg and contributors
```

Let me know if you need more information!
On a side note, thanks a lot for the Flipper Zero and its ecosystem, it is awesome!

**Comment by gsurkov** [comment]
Are you using picom (compton, xcompmgr, etc)? If yes, I would suggest trying out different settings for it (especially something mentioning "triple buffer" or "vsync"). If not, try enabling some kind of composite manager, since i3 does not do it by itself.

As a workaround, you may also use the [CLI version](https://github.com/flipperdevices/qFlipper/tree/dev/cli) (it goes bundled in the same AppImage, see link for details).

Unfortunately, there's not much else that can be done for fixing it beyond that. We are trying to support (recent) major Linux DEs, but everything extra is on the users. However, I would gladly accept any patches that fix this particular problem but do not break the rest.

If you will have further questions or bug reports, please do not hesitate to ask.
